### ISSUE TITLE
When minting a token for the 1st time the overlays stack

### ISSUE THREAD

**Issue by nephix** [raiden-network/light-client#2014] opened 2020-07-30 22:13 UTC
## Steps to Reproduce
1. Connect to new hub
2. Mint a token

## Expected Result
- Minting should be effortless

## Actual Result

When moving the cursor I encounter several tooltips (eg from the TTT token address)
The minting tooltip might get lost in translation

![Screenshot 2020-07-31 at 00 08 45](https://user-images.githubusercontent.com/3169205/88979711-84b27e00-d2c2-11ea-9ecd-e156b6523926.png)

## Additional Infos (Optional) 
```
- Browser & version
- Browser console errors
- Device / OS
```

**Comment by taleldayekh** [comment] 2020-07-31 11:50
I would be happy to get rid of all those tooltips or at a bare minimum remove the delay.

**Comment by christianbrb** [comment] 2020-08-04 09:23
Duplicate of #2026

**Closed by christianbrb** 2020-08-04 09:23 UTC
Labels: dApp 📱, enhancement
