### ISSUE TITLE
Switching network does not update the list of available token correctly

### ISSUE THREAD

**Issue by weilbith** [raiden-network/light-client#282] opened 2019-08-23 12:40 UTC
## Description
When I switch the connection from the Kovan network to Goerli, the `WETH` token remains in the list of available token, plus the `TTT` token. I would expect to see an updated list with `TTT` exclusively (at least for the current state where only a single token exist on each network).

My console error output:
```
Getting saved sync token...
Getting push rules...
Got saved sync token sync
Getting saved sync...
Got reply from saved sync, exists? false
Got push rules
Checking lazy load status...
Checking whether lazy loading has changed in store...
Storing client options...
Stored client options
Getting filter...
Unhandled promise rejection Error: "token "0xd0A1E359811322d97991E03f863a0C30C2cF029C" not monitored"
    n raiden.ts:424
    c runtime.js:45
    E runtime.js:271
    t runtime.js:97
    or app.b288bb90.js:1
    O es6.promise.js:177
    or app.b288bb90.js:1
    value app.b288bb90.js:1
    e raiden-service.ts:43
    c runtime.js:45
    E runtime.js:271
    t runtime.js:97
    o asyncToGenerator.js:5
    s asyncToGenerator.js:27
    a asyncToGenerator.js:34
    O es6.promise.js:177
    a asyncToGenerator.js:23
    t app.b288bb90.js:1
    e raiden-service.ts:109
    c runtime.js:45
    E runtime.js:271
    t runtime.js:97
    o asyncToGenerator.js:5
    s asyncToGenerator.js:27
    a asyncToGenerator.js:34
    O es6.promise.js:177
    a asyncToGenerator.js:23
    RxJS 44
    _events base-provider.js:1164
es6.promise.js:110:18
Sending first sync request...
Waiting for saved sync before starting sync processing...
```

**Comment by kelsos** [comment] 2019-08-23 14:25
@andrevmatos It should be reset on shutdown. I was there when the issue happened and I asked @weilbith to open the issue. We have to investigate what happened but my guess is also the state didn't reset properly.

**Comment by weilbith** [comment] 2019-08-23 18:00
> @weilbith can you check if this bug still happens if you ensure the URL doesn't contain the token address and reloading the page before starting the new session?

The workflow to reproduce:
- go to the landing page
- click on `connect`
- click on `connect new token` -> one token is shown in the list
- switch network -> the page automatically loads the initial / landing view
- click on `connect`
- click on `connect new token` -> two tokens are shown in the list (including the one from the previous network)

**Comment by andrevmatos** [comment] 2019-08-23 23:52
Well, your step-by-step doesn't include a full reload, so it seems state from previous session is leaking to the next run. Fix is to be sure everything is actually recreated upon these "soft restarts" as well, although a minor annoyance as you can always reload after errors (or we could force it as well, by not showing again the Connect button upon shutdown)

**Comment by christianbrb** [comment] 2019-08-27 05:39
@weilbith Is this a suitable workaround?

**Comment by weilbith** [comment] 2019-08-27 08:12
@andrevmatos I'm not 100% sure if I got your suggestion. But your note of skipping the initial connect button sounds nice. So I would be totally fine if the application reloads itself when the network has been switched. As a user I could understand that changing the blockchain cause the app to rearrange. But as said, having not to click `connect` over and over again would make it way more comfortable.

**Comment by nephix** [comment] 2019-09-26 07:20
Recently when running the light client, there's a console warning from MetaMask which might be related to this ticket:

> MetaMask: MetaMask will soon stop reloading pages on network change.
> If you rely upon this behavior, add a 'networkChanged' event handler to trigger the reload manually: https://metamask.github.io/metamask-docs/API_Reference/Ethereum_Provider#ethereum.on(eventname%2C-callback)
> Set 'ethereum.autoRefreshOnNetworkChange' to 'false' to silence this warning: https://metamask.github.io/metamask-docs/API_Reference/Ethereum_Provider#ethereum.autorefreshonnetworkchange'

**Comment by kelsos** [comment] 2019-09-26 07:39
It should be set already: https://github.com/raiden-network/light-client/blob/c6ce81305e790331606715eddd72a0f55d675168/raiden-dapp/src/services/web3-provider.ts#L13

**Comment by nephix** [comment] 2019-09-26 08:05
According to the warning setting `autoRefreshOnNetworkChange` to `false` should only prevent the warning (which doesn't seem to work)

So we probably need to listen to the `networkChanged` event in the future if we want the light client to auto reload if the network changes.

But not sure if 100% related to the issue, so sorry for derailing

**Comment by christianbrb** [comment] 2019-10-22 06:48
Not reproducible, but a new error #407 occurred

Due to the changes made in #339, the dApp is in a different status now, therefore closing it

**Closed by christianbrb** 2019-10-22 06:48 UTC
Labels: bug 💣
