### ISSUE TITLE
Cannot close modal with PFS error

### ISSUE THREAD

**Issue by taleldayekh** [raiden-network/light-client#1119] opened 2020-03-02 13:14 UTC
## Steps to Reproduce
1. Make a mediated transfer that errors

## Expected Result
- Error message to be displayed and the possibility to return and retry the transfer

## Actual Result
- Clicking the "X" does not close the modal, however, clicking outside the modal does so but it leaves the blurred overlay covering the entire window. The only way to remove it is to refresh the browser.

## Additional Infos (Optional)
![Screenshot 2020-03-02 at 14 07 30](https://user-images.githubusercontent.com/43838780/75679544-1d9b8980-5c90-11ea-8f6e-5fa132b9828c.png)
![Screenshot 2020-03-02 at 14 14 12](https://user-images.githubusercontent.com/43838780/75679549-22f8d400-5c90-11ea-8893-cfadc06cdd9c.png)

**Comment by nephix** [comment] 2020-03-02 13:35
Looks like a duplicate of #1116

**Comment by andrevmatos** [comment] 2020-03-02 13:46
Dupe of #1116

**Closed** 2020-03-03 11:38 UTC
Labels: bug 💣, dApp 📱
