### ISSUE TITLE
BF4 gets InternalServerError: timeout  for eth_getTransactionCount request

### ISSUE THREAD

**Issue by agatsoh** [raiden-network/light-client#2404] opened 2020-11-25 13:20 UTC
## Steps to Reproduce
1. 
2. 

## Expected Result
- 

## Actual Result
- 

```
{
  "task": "<OpenChannelTask: {'from': 0, 'to': 1, 'total_deposit': 1000000000000000000, 'expected_http_status': 201}>",
  "event": "Task errored",
  "logger": "scenario_player.tasks.base",
  "level": "error",
  "timestamp": "2020-11-25 00:17:47.262735",
  "exception": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.7/site-packages/scenario_player/tasks/base.py\", line 140, in __call__\n    return_val = self._run(*args, **kwargs)\n  File \"/usr/local/lib/python3.7/site-packages/scenario_player/tasks/api_base.py\", line 58, in _run\n    f'HTTP status code \"{resp.status_code}\" while fetching {url}. '\nscenario_player.exceptions.RESTAPIStatusMismatchError: HTTP status code \"500\" while fetching http://127.0.0.1:41493/api/v1/channels. Expected 201: <!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n<title>Error</title>\n</head>\n<body>\n<pre>InternalServerError: timeout (requestBody=&quot;{\\&quot;method\\&quot;:\\&quot;eth_getTransactionCount\\&quot;,\\&quot;params\\&quot;:[\\&quot;0x7a89c697172640a0eb075c2981e9c691f08004bb\\&quot;,\\&quot;pending\\&quot;],\\&quot;id\\&quot;:769,\\&quot;jsonrpc\\&quot;:\\&quot;2.0\\&quot;}&quot;, requestMethod=&quot;POST&quot;, timeout=120000, url=&quot;http://geth.goerli.ethnodes.brainbot.com:8545&quot;, code=TIMEOUT, version=web/5.0.10)<br> &nbsp; &nbsp;at Object.internalErrorHandler (/lc/index.js:254987:31)<br> &nbsp; &nbsp;at Layer.handle_error (/lc/index.js:56941:5)<br> &nbsp; &nbsp;at trim_prefix (/lc/index.js:56515:13)<br> &nbsp; &nbsp;at /lc/index.js:56484:7<br> &nbsp; &nbsp;at Function.process_params (/lc/index.js:56535:12)<br> &nbsp; &nbsp;at next (/lc/index.js:56475:10)<br> &nbsp; &nbsp;at Layer.handle_error (/lc/index.js:56937:12)<br> &nbsp; &nbsp;at trim_prefix (/lc/index.js:56515:13)<br> &nbsp; &nbsp;at /lc/index.js:56484:7<br> &nbsp; &nbsp;at Function.process_params (/lc/index.js:56535:12)</pre>\n</body>\n</html>\n"
}
```

Fails at:
```
OpenChannelTask: {'from': 0, 'to': 1, 'total_deposit': 1000000000000000000, 'expected_http_status': 201}
```

```
<!DOCTYPE html>\n
<html lang=\"en\">\n
<head>\n
	<meta charset=\"utf-8\">\n
	<title>Error</title>\n
	</head>\n
	<body>\n
		<pre>
			InternalServerError: timeout (requestBody=&quot;{\\&quot;method\\&quot;:\\&quot;eth_getTransactionCount\\&quot;,\\&quot;params\\&quot;:[\\&quot;0x7a89c697172640a0eb075c2981e9c691f08004bb\\&quot;,\\&quot;pending\\&quot;],\\&quot;id\\&quot;:769,\\&quot;jsonrpc\\&quot;:\\&quot;2.0\\&quot;}&quot;, requestMethod=&quot;POST&quot;, timeout=120000, url=&quot;http://geth.goerli.ethnodes.brainbot.com:8545&quot;, code=TIMEOUT, version=web/5.0.10)<br> 
			&nbsp; &nbsp;at Object.internalErrorHandler (/lc/index.js:254987:31)<br> 
			&nbsp; &nbsp;at Layer.handle_error (/lc/index.js:56941:5)<br> 
			&nbsp; &nbsp;at trim_prefix (/lc/index.js:56515:13)<br> 
			&nbsp; &nbsp;at /lc/index.js:56484:7<br> 
			&nbsp; &nbsp;at Function.process_params (/lc/index.js:56535:12)<br> 
			&nbsp; &nbsp;at next (/lc/index.js:56475:10)<br> 
			&nbsp; &nbsp;at Layer.handle_error (/lc/index.js:56937:12)<br> 
			&nbsp; &nbsp;at trim_prefix (/lc/index.js:56515:13)<br> 
			&nbsp; &nbsp;at /lc/index.js:56484:7<br> 
			&nbsp; &nbsp;at Function.process_params (/lc/index.js:56535:12)
		</pre>\n
	</body>\n
</html>\n"
```

InternalServerError: timeout (
requestBody=";{";method";:";eth_getTransactionCount";,";params";:[";0x7a89c697172640a0eb075c2981e9c691f08004bb";,";pending";],";id";:769,";jsonrpc";:";2.0";}";, requestMethod=";POST";, timeout=120000, url=";http://geth.goerli.ethnodes.brainbot.com:8545";, code=TIMEOUT, version=web/5.0.10)

[scenario-player-run_bf4_multi_payments_same_node_2020-11-25T00:12:11.log](https://github.com/raiden-network/light-client/files/5596888/scenario-player-run_bf4_multi_payments_same_node_2020-11-25T00.12.11.log)

**Comment by christianbrb** [comment] 2020-11-25 13:44
Duplicate of https://github.com/raiden-network/light-client/issues/2388

**Closed by christianbrb** 2020-11-25 13:44 UTC
Labels: bug 🕷️, scenario 🤖
