### ISSUE TITLE
SDK misses MetaMask transfer reverted exception

### ISSUE THREAD

**Issue by weilbith** [raiden-network/light-client#2728] opened 2021-05-19 13:56 UTC
## Description

How to reproduce:
- put the following into your dApp's '.env.development` file (this config is broken/invalid):
   ```sh
   VUE_APP_PFS=https://pfs.demo001.env.raiden.network
   VUE_APP_MATRIX_SERVER=https://transport.demo001.env.raiden.network
   VUE_APP_UDC_ADDRESS=0x0794F09913AA8C77C8c5bdd1Ec4Bb51759Ee0cC5
   ```
- connect to the dApp with this config and use the injected provider using Goerli
- try to mint some tokens 
- check the browsers dev console to see the error by MetaMask: `MetaMask - RPC Error: execution reverted 
Object { code: -32000, message: "execution reverted" }`
- the mint dialog is still loading and the SDK waits for the transaction response

## Acceptance criteria
- 

## Tasks
- [ ]

**Comment by weilbith** [comment] 2021-05-19 13:56
@andrevmatos here --^

**Comment by andrevmatos** [comment] 2021-05-21 00:25
I still couldn't reproduce. Maybe this could be the log of an old tx. What I'm seeing is Goerli being very slow currently, which makes the LC take a long time to submit a tx, while your client could have detected an old queued action (maybe a past udc/withdraw plan or something like that). I'll continue to investigate.

**Comment by weilbith** [comment] 2021-05-21 09:22
Okay, stop working on it. I think we have more important stuff atm to do. When I encounter this issue again I'll ping you.

**Comment by andrevmatos** [comment] 2021-05-24 20:32
So, I've tried to reproduce this again with an explicit rejection on Metamask's request, and the error was properly propagated. I suppose the minting getting stuck you saw is due to Goerli's slowness these times, the error message is unrelated and possibly caused by the retry loop of some old tx also caused by Goerli state. Let's close this, and reopen if we see this on this week's test by hand on testnet & mainnet.

**Closed by andrevmatos** 2021-05-24 20:32 UTC
Labels: bug 🕷️, sdk 🖥
