### ISSUE TITLE
404 error while downloading `/img/icons/apple-touch-icon-152x152.png`

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#2384] opened 2020-11-23 08:58 UTC
## Steps to Reproduce
1. Disable cache
2. Open the dApp

## Expected Result
- No 404 errors

## Actual Result
- 404 error while downloading `/img/icons/apple-touch-icon-152x152.png`

![grafik](https://user-images.githubusercontent.com/35398162/99943963-69d4af80-2d72-11eb-8777-16721bf1d2cd.png)

## Additional Infos (Optional) 
```
- Browser & version
- Browser console errors
- Device / OS
```

**Comment by agatsoh** [comment] 2021-02-15 13:56
@taleldayekh this issue is not really reproducible by me, infact at this point there is no `apple-touch-icon-152x152.png` image
but yes I have got these errors
these are 
`401` --> `displayname` 
`429` --> `avatar_url`
errors and not serious errors that we should look into. They do not affect the functioning of the app at all.
![lc_access_avatar_url_discovery](https://user-images.githubusercontent.com/15123108/107955100-63498300-6fc3-11eb-9839-a732ba5c1d9a.png)

**Comment by agatsoh** [comment] 2021-02-15 14:20
Seems like only happens for apple devices 
https://stackoverflow.com/questions/12480497/why-am-i-getting-error-for-apple-touch-icon-precomposed-png

https://statamic.com/forum/1488-how-to-get-rid-of-apple-touch-iconpng-fl

**Comment by taleldayekh** [comment] 2021-02-15 14:23
Ok, thank you @agatsoh . Then we will keep the issue open, I'll assign myself and look into it on my mac.

**Comment by taleldayekh** [comment] 2021-02-18 09:10
Ok, I cannot reproduce this either. I tried disable the cache and loaded the dApp in Safari, Chrome, Brave and Firefox. Also, we don't have any touch icon defined in the header tag. In fact, I am not getting any 404s.

Closing issues, open again if anyone encounters this.

**Closed by taleldayekh** 2021-02-18 09:10 UTC
Labels: bug 🕷️, dApp 📱, minor
