### ISSUE TITLE
Create info window for progress tracker (stepper) of channel states

### ISSUE THREAD

**Issue by roy-castrillo** [raiden-network/light-client#184] opened 2019-06-18 10:30 UTC
## Description
Some buttons are active and/or inactive depending on the channel state (open, closed, settleable). Adding an info icon leading to an info window will help users quickly understand what these states mean, and most importantly what each one of them allows them to do.

## Acceptance criteria
- Icon should appear somewhere in the channel list. 
  - Integrate it as part of the top bar? 
  - Add a 'floating' (fixed) button-like icon?
- All three stated should be described.

## Tasks
- [ ] Design
- [ ] Implementation

**Comment by christianbrb** [comment] 2019-12-06 11:30
Duplicate of #269

**Closed by christianbrb** 2019-12-06 11:30 UTC
Labels: Design 🖌
