### ISSUE TITLE
BF1 gets No route between nodes found

### ISSUE THREAD

**Issue by agatsoh** [raiden-network/light-client#2433] opened 2020-12-04 13:00 UTC
## Steps to Reproduce
1. 
2. 

## Expected Result
- 

## Actual Result
- 

```
{
  "task": "<TransferTask: {'from': 3, 'to': 0, 'amount': 1000000000000000, 'lock_timeout': 30, 'identifier': 149028145071000002}>",
  "event": "Task errored",
  "logger": "scenario_player.tasks.base",
  "level": "error",
  "greenlet_name": "orchestration",
  "timestamp": "2020-12-03 23:13:48.918209",
  "exception": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.7/site-packages/scenario_player/tasks/base.py\", line 140, in __call__\n    return_val = self._run(*args, **kwargs)\n  File \"/usr/local/lib/python3.7/site-packages/scenario_player/tasks/api_base.py\", line 59, in _run\n    f'HTTP status code \"{resp.status_code}\" while fetching {url}. '\nscenario_player.exceptions.RESTAPIStatusMismatchError: HTTP status code \"409\" while fetching http://127.0.0.1:43433/api/v1/payments/0x59105441977ecD9d805A4f5b060E34676F50F806/0xe043445533B6e654CB372FfD85A0cE76d0128E85. Expected 2..: {\"message\":\"No route between nodes found.\",\"details\":\"\"}"
}
```

Fails in the transfer task
```
TransferTask: {'from': 3, 'to': 0, 'amount': 1000000000000000, 'lock_timeout': 30, 'identifier': 149028145071000002}
```

From logs of node3

```
payload: RaidenError: No route between nodes found.
      at /lc/index.js:249268:23
      at Generator.next (<anonymous>)
      at Observable._subscribe (/lc/index.js:209078:29)
      at Observable._trySubscribe (/lc/index.js:198183:25)
      at Observable.subscribe (/lc/index.js:198169:22)
      at Object.innerSubscribe (/lc/index.js:199250:23)
      at MergeMapSubscriber.module.exports.__webpack_modules__.42713.MergeMapSubscriber._innerSub (/lc/index.js:204040:50)
      at MergeMapSubscriber.module.exports.__webpack_modules__.42713.MergeMapSubscriber._tryNext (/lc/index.js:204034:14)
      at MergeMapSubscriber.module.exports.__webpack_modules__.42713.MergeMapSubscriber._next (/lc/index.js:204017:18)
      at MergeMapSubscriber.module.exports.__webpack_modules__.65183.Subscriber.next (/lc/index.js:198786:18) {
    details: {}
  },
  meta: {
    tokenNetwork: '0x3EA2a1fED7FdEf300DA19E97092Ce8FdF8bf66A3',
    target: '0xe043445533B6e654CB372FfD85A0cE76d0128E85',
    value: BigNumber { _hex: '0x038d7ea4c68000', _isBigNumber: true }
  },
  error: true
}
```
[scenario-player-run_bf1_basic_functionality_2020-12-03T23:05:40.log](https://github.com/raiden-network/light-client/files/5642861/scenario-player-run_bf1_basic_functionality_2020-12-03T23.05.40.log)

node logs

[bf1_node3_node0_4thDec2020.tar.gz](https://github.com/raiden-network/light-client/files/5642863/bf1_node3_node0_4thDec2020.tar.gz)

**Comment by andrevmatos** [comment] 2020-12-04 14:56
This seem to be the Presence bug on the PFS, not caused by our code. May have been improved by #2417, let's see if the next runs still hit this.

**Comment by christianbrb** [comment] 2020-12-18 14:24
Did not occur during the last days

**Comment by agatsoh** [comment] 2021-01-07 11:20
Occured today on PFS6 7th Jan 2021 logs are attached

[scenario-player-run_pfs6_simple_path_rewards_2021-01-07T05:25:48.log](https://github.com/raiden-network/light-client/files/5781256/scenario-player-run_pfs6_simple_path_rewards_2021-01-07T05.25.48.log)


[pfs6_node0_node3_07Jan2021.tar.gz](https://github.com/raiden-network/light-client/files/5781259/pfs6_node0_node3_07Jan2021.tar.gz)

**Comment by agatsoh** [comment] 2021-01-07 11:27
Occurred in BF1 today 7th Jan 2021 logs are attached

[scenario-player-run_bf1_basic_functionality_2021-01-06T23:06:53.log](https://github.com/raiden-network/light-client/files/5781292/scenario-player-run_bf1_basic_functionality_2021-01-06T23.06.53.log)
[bf1_node0_node3_7thJan2021.tar.gz](https://github.com/raiden-network/light-client/files/5781293/bf1_node0_node3_7thJan2021.tar.gz)

**Comment by agatsoh** [comment] 2021-01-25 09:57
this occured today 25th Jan 2021 In BF1  and BF7
Logs are attached 

BF1 logs attached
[scenario-player-run_bf1_basic_functionality_2021-01-24T21:02:28.log](https://github.com/raiden-network/light-client/files/5865673/scenario-player-run_bf1_basic_functionality_2021-01-24T21.02.28.log)

[node_4619_003.tar.gz](https://github.com/raiden-network/light-client/files/5865677/node_4619_003.tar.gz)

**Comment by agatsoh** [comment] 2021-01-27 11:04
Again occured today on BF6, BF7, PFS1

**Comment by andrevmatos** [comment] 2021-02-01 13:38
These were caused by infrastructure issues. Matrix purge + PFS fixes seem to have fixed it on last night's run.

**Comment by palango** [comment] 2021-03-23 08:39
Closing as all three were green again tonight.

**Closed by palango** 2021-03-23 08:39 UTC
Labels: 8, bug 🕷️, scenario 🤖
