### ISSUE TITLE
Channel status on channel screen appearantly not shown right

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#484] opened 2019-11-04 11:30 UTC
## Steps to Reproduce
1. Close a channel
2. Sign transactions with MetaMask
3. Wait untile the transaction is mined (console log)

## Expected Result
- Channel is shown as settleable
- Close button is not active
- Settle button is active

## Actual Result
- Close button is active
- Channel is shown with `State: Closing`
- Close button is active
- Settle button is not active
    
![grafik](https://user-images.githubusercontent.com/35398162/68117826-b565b280-fefe-11e9-9293-c284ec7a1850.png)

## Additional Infos (Optional) 

[lightclient.raiden.network-1572866912496.log](https://github.com/raiden-network/light-client/files/3803755/lightclient.raiden.network-1572866912496.log)

Account: 0xB84C6bFBA1108543Ea47e8B9a669CB39ffc70f6A
Testnet: Goerli
Transactions: https://goerli.etherscan.io/address/0xb84c6bfba1108543ea47e8b9a669cb39ffc70f6a

**Comment by kelsos** [comment] 2019-11-04 11:41
@christianbrb isn't it way to fast for the channel to become settleable? I still see the closing transaction at 110 blocks ago. We have to wait for 500 blocks for the channel to become settleable after closing it.

**Comment by christianbrb** [comment] 2019-11-04 11:51
@kelsos Thanks for your answer

`Closing `is the `settle_timeout` waiting period

My current understanding:
Closed = Close Transaction was successful
Closing = Waiting for `settle_timeout`
Settleable = `settle_timeout` has passed

**Comment by christianbrb** [comment] 2019-11-04 13:22
Closing this issue in favor of a follow up issue https://github.com/raiden-network/light-client/issues/489

**Comment by christianbrb** [comment] 2019-11-04 16:26
Reopening as channel not closed yet. Checking in tomorrow morning

**Comment by christianbrb** [comment] 2019-11-06 06:44
Today the channel is still in the same state. Maybe related to #497

**Comment by andrevmatos** [comment] 2019-11-06 15:29
`Closing` is actually waiting for the `close` tx, which may fail and may be performed again. Once it's mined, channel goes to `Closed` state and stays there until becoming `Settleable`. The fact that it's still closing and didn't become `Closed` after tx was mined may indicate a fail at getting the event, which should be fixed by #497, although fixing your state may require either cleaning it (if you don't have other relevant channels) or forcing it to fetch events since a block before the close tx: for this, as a temporary workaround to avoid clearing whole state if not desired (because other channels may be open):
- open the dApp
- before clicking `Connect`, open browser's DevTools, go to `Application` and local storage
- search for `raiden_goerli_..._<account_address>` key
- double click to edit the value
- search for `blockNumber` key (should be close to top), and edit its value to a block number before your closeTx
- no need to reload, just click Connect and check your channel state, should be correct as `Settleable`

**Comment by andrevmatos** [comment] 2019-11-06 15:30
If you don't have other useful channels, you can safely just clear local storage, on next startup (as per #497), the channels state will be refetched correctly and you can proceed from there with settling and opening a new channel.

**Comment by andrevmatos** [comment] 2019-11-06 15:30
Marking as Closed by #497, reopen if issue persist, please. Sorry for the inconvenient, I'm monitoring if this kind of issue happen again, but seems that PR may have fixed it for good.

**Closed by andrevmatos** 2019-11-06 15:30 UTC
Labels: bug 💣

**Comment by christianbrb** [comment] 2019-11-11 07:56
@taleldayekh Could you try to reproduce the issue?

**Comment by taleldayekh** [comment] 2019-11-11 08:49
Sure, I'll have a look.

**Comment by taleldayekh** [comment] 2019-11-11 16:47
To me everything works as expected @christianbrb .

After closing a channel I get:
- Close button is **not** active
- After mining is done (approx 2 hours) the settle button **is** active

I can from there settle the channel without any problem. So by going through the flow I can't reproduce the issue.

**Comment by christianbrb** [comment] 2019-11-11 20:48
Cool :) Thanks for checking it.
