### ISSUE TITLE
BF7 error cannot estimate gas transaction may fail or may require manual gas limit

### ISSUE THREAD

**Issue by agatsoh** [raiden-network/light-client#2402] opened 2020-11-25 11:18 UTC
## Steps to Reproduce
1. 
2. 

## Expected Result
- 

## Actual Result
- 
```
{
  "task": "<OpenChannelTask: {'from': 2, 'to': 3, 'total_deposit': 1000000000000000000}>",
  "event": "Task errored",
  "logger": "scenario_player.tasks.base",
  "level": "error",
  "timestamp": "2020-11-25 01:27:25.622579",
  "exception": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.7/site-packages/scenario_player/tasks/base.py\", line 140, in __call__\n    return_val = self._run(*args, **kwargs)\n  File \"/usr/local/lib/python3.7/site-packages/scenario_player/tasks/api_base.py\", line 58, in _run\n    f'HTTP status code \"{resp.status_code}\" while fetching {url}. '\nscenario_player.exceptions.RESTAPIStatusMismatchError: HTTP status code \"500\" while fetching http://127.0.0.1:36171/api/v1/channels. Expected 2..: <!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n<title>Error</title>\n</head>\n<body>\n<pre>InternalServerError: cannot estimate gas; transaction may fail or may require manual gas limit (error={&quot;reason&quot;:&quot;cannot estimate gas; transaction may fail or may require manual gas limit&quot;,&quot;code&quot;:&quot;UNPREDICTABLE_GAS_LIMIT&quot;,&quot;error&quot;:{&quot;reason&quot;:&quot;processing response error&quot;,&quot;code&quot;:&quot;SERVER_ERROR&quot;,&quot;body&quot;:&quot;{\\&quot;jsonrpc\\&quot;:\\&quot;2.0\\&quot;,\\&quot;id\\&quot;:594,\\&quot;error\\&quot;:{\\&quot;code\\&quot;:-32000,\\&quot;message\\&quot;:\\&quot;execution reverted\\&quot;}}\\n&quot;,&quot;error&quot;:{&quot;code&quot;:-32000},&quot;requestBody&quot;:&quot;{\\&quot;method\\&quot;:\\&quot;eth_estimateGas\\&quot;,\\&quot;params\\&quot;:[{\\&quot;gasPrice\\&quot;:\\&quot;0x4d7c6d00\\&quot;,\\&quot;from\\&quot;:\\&quot;0x4719376ca94512a8a5cc6d52404a7b753a8feaad\\&quot;,\\&quot;to\\&quot;:\\&quot;0x3ea2a1fed7fdef300da19e97092ce8fdf8bf66a3\\&quot;,\\&quot;data\\&quot;:\\&quot;0x0a798f240000000000000000000000004719376ca94512a8a5cc6d52404a7b753a8feaad0000000000000000000000005302ee87670e3db100fb7567bc547b70cb2f70ae00000000000000000000000000000000000000000000000000000000000001f4\\&quot;}],\\&quot;id\\&quot;:594,\\&quot;jsonrpc\\&quot;:\\&quot;2.0\\&quot;}&quot;,&quot;requestMethod&quot;:&quot;POST&quot;,&quot;url&quot;:&quot;http://geth.goerli.ethnodes.brainbot.com:8545&quot;},&quot;method&quot;:&quot;estimateGas&quot;,&quot;transaction&quot;:{&quot;from&quot;:&quot;0x4719376ca94512A8a5cc6D52404a7b753a8feAAd&quot;,&quot;gasPrice&quot;:{&quot;type&quot;:&quot;BigNumber&quot;,&quot;hex&quot;:&quot;0x4d7c6d00&quot;},&quot;to&quot;:&quot;0x3EA2a1fED7FdEf300DA19E97092Ce8FdF8bf66A3&quot;,&quot;data&quot;:&quot;0x0a798f240000000000000000000000004719376ca94512a8a5cc6d52404a7b753a8feaad0000000000000000000000005302ee87670e3db100fb7567bc547b70cb2f70ae00000000000000000000000000000000000000000000000000000000000001f4&quot;}}, tx={&quot;data&quot;:&quot;0x0a798f240000000000000000000000004719376ca94512a8a5cc6d52404a7b753a8feaad0000000000000000000000005302ee87670e3db100fb7567bc547b70cb2f70ae00000000000000000000000000000000000000000000000000000000000001f4&quot;,&quot;to&quot;:{},&quot;from&quot;:&quot;0x4719376ca94512A8a5cc6D52404a7b753a8feAAd&quot;,&quot;gasPrice&quot;:{},&quot;nonce&quot;:{},&quot;gasLimit&quot;:{},&quot;chainId&quot;:{}}, code=UNPREDICTABLE_GAS_LIMIT, version=abstract-signer/5.0.8)<br> &nbsp; &nbsp;at Object.internalErrorHandler (/lc/index.js:254987:31)<br> &nbsp; &nbsp;at Layer.handle_error (/lc/index.js:56941:5)<br> &nbsp; &nbsp;at trim_prefix (/lc/index.js:56515:13)<br> &nbsp; &nbsp;at /lc/index.js:56484:7<br> &nbsp; &nbsp;at Function.process_params (/lc/index.js:56535:12)<br> &nbsp; &nbsp;at next (/lc/index.js:56475:10)<br> &nbsp; &nbsp;at Layer.handle_error (/lc/index.js:56937:12)<br> &nbsp; &nbsp;at trim_prefix (/lc/index.js:56515:13)<br> &nbsp; &nbsp;at /lc/index.js:56484:7<br> &nbsp; &nbsp;at Function.process_params (/lc/index.js:56535:12)</pre>\n</body>\n</html>\n"
}
```

Fails at:
OpenChannelTask: {'from': 2, 'to': 3, 'total_deposit': 1000000000000000000}

```
- open_channel: {from: 2, to: 3, total_deposit: 1_000_000_000_000_000_000}
```

```
<!DOCTYPE html>\n
<html lang=\"en\">\n
<head>\n
	<meta charset=\"utf-8\">
	<title>Error</title>
	</head>
	<body>
		<pre>InternalServerError: cannot estimate gas; transaction may fail or may require manual gas limit (error={&quot;reason&quot;:&quot;cannot estimate gas; transaction may fail or may require manual gas limit&quot;,&quot;code&quot;:&quot;UNPREDICTABLE_GAS_LIMIT&quot;,&quot;error&quot;:{&quot;reason&quot;:&quot;processing response error&quot;,&quot;code&quot;:&quot;SERVER_ERROR&quot;,&quot;body&quot;:&quot;{\\&quot;jsonrpc\\&quot;:\\&quot;2.0\\&quot;,\\&quot;id\\&quot;:594,\\&quot;error\\&quot;:{\\&quot;code\\&quot;:-32000,\\&quot;message\\&quot;:\\&quot;execution reverted\\&quot;}}\
			&quot;,&quot;error&quot;:{&quot;code&quot;:-32000},&quot;requestBody&quot;:&quot;{\\&quot;method\\&quot;:\\&quot;eth_estimateGas\\&quot;,\\&quot;params\\&quot;:[{\\&quot;gasPrice\\&quot;:\\&quot;0x4d7c6d00\\&quot;,\\&quot;from\\&quot;:\\&quot;0x4719376ca94512a8a5cc6d52404a7b753a8feaad\\&quot;,\\&quot;to\\&quot;:\\&quot;0x3ea2a1fed7fdef300da19e97092ce8fdf8bf66a3\\&quot;,\\&quot;data\\&quot;:\\&quot;0x0a798f240000000000000000000000004719376ca94512a8a5cc6d52404a7b753a8feaad0000000000000000000000005302ee87670e3db100fb7567bc547b70cb2f70ae00000000000000000000000000000000000000000000000000000000000001f4\\&quot;}],\\&quot;id\\&quot;:594,\\&quot;jsonrpc\\&quot;:\\&quot;2.0\\&quot;}&quot;,&quot;requestMethod&quot;:&quot;POST&quot;,&quot;url&quot;:&quot;http://geth.goerli.ethnodes.brainbot.com:8545&quot;},&quot;method&quot;:&quot;estimateGas&quot;,&quot;transaction&quot;:{&quot;from&quot;:&quot;0x4719376ca94512A8a5cc6D52404a7b753a8feAAd&quot;,&quot;gasPrice&quot;:{&quot;type&quot;:&quot;BigNumber&quot;,&quot;hex&quot;:&quot;0x4d7c6d00&quot;},&quot;to&quot;:&quot;0x3EA2a1fED7FdEf300DA19E97092Ce8FdF8bf66A3&quot;,&quot;data&quot;:&quot;0x0a798f240000000000000000000000004719376ca94512a8a5cc6d52404a7b753a8feaad0000000000000000000000005302ee87670e3db100fb7567bc547b70cb2f70ae00000000000000000000000000000000000000000000000000000000000001f4&quot;}}, tx={&quot;data&quot;:&quot;0x0a798f240000000000000000000000004719376ca94512a8a5cc6d52404a7b753a8feaad0000000000000000000000005302ee87670e3db100fb7567bc547b70cb2f70ae00000000000000000000000000000000000000000000000000000000000001f4&quot;,&quot;to&quot;:{},&quot;from&quot;:&quot;0x4719376ca94512A8a5cc6D52404a7b753a8feAAd&quot;,&quot;gasPrice&quot;:{},&quot;nonce&quot;:{},&quot;gasLimit&quot;:{},&quot;chainId&quot;:{}}, code=UNPREDICTABLE_GAS_LIMIT, version=abstract-signer/5.0.8)<br> 
			&nbsp; &nbsp;at Object.internalErrorHandler (/lc/index.js:254987:31)<br> 
			&nbsp; &nbsp;at Layer.handle_error (/lc/index.js:56941:5)<br> 
			&nbsp; &nbsp;at trim_prefix (/lc/index.js:56515:13)<br> 
			&nbsp; &nbsp;at /lc/index.js:56484:7<br> 
			&nbsp; &nbsp;at Function.process_params (/lc/index.js:56535:12)<br> 
			&nbsp; &nbsp;at next (/lc/index.js:56475:10)<br> 
			&nbsp; &nbsp;at Layer.handle_error (/lc/index.js:56937:12)<br> 
			&nbsp; &nbsp;at trim_prefix (/lc/index.js:56515:13)<br> 
			&nbsp; &nbsp;at /lc/index.js:56484:7<br> 
			&nbsp; &nbsp;at Function.process_params (/lc/index.js:56535:12)
		</pre>
	</body>
</html>\n"
```

**InternalServerError: cannot estimate gas; transaction may fail or may require manual gas limit**

request `eth_estimateGas`

[scenario-player-run_bf7_long_path_2020-11-25T01:22:53.log](https://github.com/raiden-network/light-client/files/5596314/scenario-player-run_bf7_long_path_2020-11-25T01.22.53.log)

**Comment by christianbrb** [comment] 2020-11-25 13:43
Duplicate of https://github.com/raiden-network/light-client/issues/2388

**Comment by agatsoh** [comment] 2020-11-30 08:38
Got to observe this error today 

Scenario logs
[scenario-player-run_bf7_long_path_2020-11-30T00:25:13.log](https://github.com/raiden-network/light-client/files/5614661/scenario-player-run_bf7_long_path_2020-11-30T00.25.13.log)


Node logs
[bf7_node10_node11_30thNov2020.tar.gz](https://github.com/raiden-network/light-client/files/5614675/bf7_node10_node11_30thNov2020.tar.gz)

**Comment by andrevmatos** [comment] 2020-11-30 15:48
Ok, it seems this issue is related to #2403 
It could reproduce it by running BF7 with `geth` node only, but **not** by running all nodes on `parity`, so it seems to confirm this and that other issue as infrastructure issues on the `geth` node. Retrying the requests and giving more timeout (on the WIP in the linked PR) did **not** fix the issue, I witnessed `ChannelOpened` events being lost even though they were present on `etherscan`, so either the node did not see the event, or timed out on the respective `getLogs` calls, but weird enough, both sides of the channel did not see it, so it points again to infrastructure issue on these high-load scenarios.
I'll continue investigating if the node didn't get the event, the event didn't make it to the `getLogs` calls, or the `getLogs` calls itself failed/hang forever.

**Closed** 2020-12-04 11:52 UTC
Labels: bug 🕷️, scenario 🤖
