### ISSUE TITLE
Update eslint rules

### ISSUE THREAD

**Issue by nephix** [raiden-network/light-client#1332] opened 2020-04-15 07:05 UTC
## Description

Follow up to https://github.com/raiden-network/light-client/pull/1308#discussion_r408617114
We should enforce a couple more linting rules throughout the code base

## Acceptance criteria
- Self closing tags should be enforced: https://github.com/vuejs/eslint-plugin-vue/blob/master/docs/rules/html-self-closing.md
- Enforce import ordering on the dApp
- Added (@andrevmatos): enforce lodash import style

## Tasks
- [x] Implement new rules
- [x] Check why `order/import` does not work in SDK tests https://github.com/raiden-network/light-client/pull/1315/files#r411426482

**Comment by nephix** [comment] 2020-04-16 09:39
There is also https://github.com/cartant/rxjs-tslint-rules which could be used to avoid bad imports (e.g. from `rxjs/internal/...` through `rxjs-no-internal`) which could help with bundle size in #744

**Comment by kelsos** [comment] 2020-04-16 10:33
there seems to be an eslint compatible package too from a quick look https://github.com/cartant/eslint-plugin-rxjs so we should certainly consider that

**Comment by christianbrb** [comment] 2020-08-07 08:01
@andrevmatos @weilbith Is this issue still needed?

**Comment by kelsos** [comment] 2020-08-07 08:04
From what I remember, the import order is half-working, but not on everything

**Comment by weilbith** [comment] 2020-08-07 08:40
Yes, definitely still a thing. In general we should revisit our linting for all projects once we have time for such things. I think there is definitely room for improvement.

**Comment by christianbrb** [comment] 2020-08-07 08:43
Is this one a duplicate or just related? -> https://github.com/raiden-network/light-client/issues/1864

**Comment by kelsos** [comment] 2020-08-07 08:46
I would say just related. This one is about adding some more rules, the other issue is about extracting a common base for all the rules that are common between the dapp/cli/sdk.

**Comment by palango** [comment] 2021-01-05 12:13
- the [self closing](https://github.com/vuejs/eslint-plugin-vue/blob/master/docs/rules/html-self-closing.md#vuehtml-self-closing) lint is included in the `plugin:vue/recommended` ruleset, which is enabled in the dApp.
- Sorted imports are done as well. @weilbith @andrevmatos can you confirm this?

**Comment by nephix** [comment] 2021-01-05 17:12
iirc import ordering was in the dApps eslint config but didn't work at the time when the ticket got created. Not sure about current state

**Comment by andrevmatos** [comment] 2021-01-05 17:57
The import ordering is present, but is a little bit naive. The eslint plugin can be tweaked to enforce a more specific order, i.e. enforcing relative-level ordering and same-level alphabetical ordering (currently, iianm, it only sorts between siblings, upper-level and external imports). Other than that, we should also check if these rules applies correctly to imports inside Vue's SFCs.

**Comment by weilbith** [comment] 2021-01-06 10:29
> The import ordering is present, but is a little bit naive.

I can confirm that. I like deterministic formatting with a strict order. Also it treats the group of relative imports "higher" (in terms of the order in the file) than imports with a global alias. At least I find that weird since I think relative imports should be only used for super close module relations where you are sure they will stick together in the source tree as they are. So never go upwards the directory structure (i.e. `import Something from "../<what-ever>").

**Closed** 2021-02-12 21:29 UTC
