### ISSUE TITLE
SecretRequest for amount too small

### ISSUE THREAD

**Issue by nephix** [raiden-network/light-client#397] opened 2019-10-17 14:05 UTC
## Steps to Reproduce
1. Start two raiden v0.200.0-rc1 clients
2. Start light client
3. Establish & fund channels between light client <-> 1st raiden client <-> 2nd raiden client
4. Try to pay 2nd raiden client from light client

## Expected Result
- Payment goes through
- No errors in console

## Actual Result
- Payment "gets stuck"
- Warning in console **SecretRequest for amount  too small!**

![amount-too-small](https://user-images.githubusercontent.com/3169205/67015769-57139400-f0f7-11e9-9b48-1169f0b0b936.png)

## Additional Infos

- Amount typed into light client: `0.000000011000000000`
- Fees displayed in light client: `0.000000000251947751`
- Total Amount in light client: `0.000000011251947751`
- Amount in warning: `0x028fa62a04` is `0.000000010999966212`

I'm passing the amount `0.000000011000000000` to the SDK's `transfer()` method and the route that includes the fee of `0.000000000251947751`.

When trying it with a smaller amount (`0.000000000000000100`) it somehow worked, so it's not reproducible 100% of the time.

Console output:
[localhost-1571298604780.log](https://github.com/raiden-network/light-client/files/3739689/localhost-1571298604780.log)

**Comment by andrevmatos** [comment] 2019-10-18 00:26
As can be seen by the amount in the warning, the amount which arrived in target and was informed in `SecretRequest` was smaller than what was expected to be sent after fees, and therefore the warning means we're not revealing the secret and the transfer will need to expire.
We got the estimated fee from the PFS. The mediator effectively tried to take more in fees than the PFS estimated. This is not in our side, but on Raiden or PFS side. May be caused by one of them being outdated in relation to the others and the latest changes in fee calculation. Needs to be tested, but our side definitively acted as expected: added the fee received from PFS to the amount and sent it, and when received less than expected, warned and didn't reveal the secret.

**Comment by nephix** [comment] 2019-10-18 03:31
In #246 we had the acceptance criteria that we should:

> Send the amount + expected fees provided by PFS + 10%

Currently we don't send the additional 10% but I think it could solve the problem?

**Comment by christianbrb** [comment] 2019-10-18 06:04
There have been some [changes ](https://github.com/raiden-network/raiden/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Amerged+merged%3A%3E2019-10-04+fee*+) recently within the client regarding fees

@palango @karlb Any idea what caused the behavior [above](https://github.com/raiden-network/light-client/issues/397#issue-508500165)?

**Comment by nephix** [comment] 2019-10-18 08:38
The 10% increase of the suggested fee fetched from PFS makes the payments work reliably, with the downside of the target receiving more than the initiator has entered. 

Some actual numbers for a 1-hop payment:
```
Amount in LC:       0.000000011000000000
Fee from PFS:       0.000000000251947751
10% increased Fee:  0.000000000277142526
Total Sent from LC: 0.000000011277142526
Target received:    0.000000011024596764
```

IIRC this was one of the tradeoffs mentioned by the services team.

**Comment by christianbrb** [comment] 2019-10-18 13:11
## Acceptance Criteria
- Add a safety margin of 10% (expressed as 1.1) in the config
- The default of safety margin is 1
- The dApp will set the safety margin to 1.1

**Comment by karlb** [comment] 2019-10-18 14:21
Yes, clients are expected to add a safety margin to the mediation fees. The Raiden client currently uses https://github.com/raiden-network/raiden/blob/cdf0143885264f7e67b54400b23b914f9c198052/raiden/transfer/mediated_transfer/initiator.py#L61

Today's merged PRs increased the accuracy of the fee calculations a lot, so that fee calculations differ no more than 1 Token between PFS and mediator. However, the margin should still be larger to compensate for changes in imbalance fees that happen between the time of the route calculation and the time of the mediation. We plan to introduce recommended fee margins in the PFS response to make it easier for the client and to choose the margins in a smarter way (https://github.com/raiden-network/raiden-services/issues/569).

**Closed as completed** 2019-10-24 06:54 UTC
Labels: bug 🕷️, 2, sdk 🖥
