### ISSUE TITLE
BF1 gets Requested target is offline message 

### ISSUE THREAD

**Issue by agatsoh** [raiden-network/light-client#2294] opened 2020-10-28 08:32 UTC
## Thanks for filing a bug report :-)
28Oct2020
## Steps to Reproduce
1. 
2. 

## Expected Result
- 

## Actual Result
- 
```
HTTP status code “409” while fetching http://127.0.0.1:57957/api/v1/payments/0x59105441977ecD9d805A4f5b060E34676F50F806/0xcb902E222EA41EdB748b31c3425E3736Ac08d60A. Expected 2..: {“message”:”The requested target is offline.”,”details”:””}
```
Logs have to be uploaded

**Comment by andrevmatos** [comment] 2020-10-28 10:55
Hmm, this is caused by the presence bug. We did decrease it by a lot with our workarounds, but seems it still got triggered somehow, maybe because of other parallel runs.

**Comment by christianbrb** [comment] 2020-10-28 13:28
Issue might be in the PFS due to the matrix presence bug.

**Comment by christianbrb** [comment] 2020-11-02 14:29
Duplicate of #2305

**Closed by christianbrb** 2020-11-02 14:29 UTC
Labels: bug 💣, scenario 🤖
