### ISSUE TITLE
Text on UDC screen not aligned

### ISSUE THREAD

**Issue by nephix** [raiden-network/light-client#2013] opened 2020-07-30 22:10 UTC
## Steps to Reproduce
1. Connect
2. Click settings
3. Go to udc screen

## Expected Result
- Text is aligned within grid

## Actual Result
![Screenshot 2020-07-30 at 23 57 35](https://user-images.githubusercontent.com/3169205/88979548-38ffd480-d2c2-11ea-998b-549200e7dace.png)

## Additional Infos (Optional) 
```
- Browser & version
- Browser console errors
- Device / OS
```

**Comment by taleldayekh** [comment] 2020-07-31 08:56
Thank you for filing a bug report @nephix . We miss you over here. :) The UDC has been reworked a bit and looks like this now:
<img width="670" alt="Screenshot 2020-07-31 at 10 54 54" src="https://user-images.githubusercontent.com/43838780/89018632-73965b00-d31c-11ea-9859-2bfbe15a3b22.png">

**Comment by nephix** [comment] 2020-07-31 09:02
Thank you @taleldayekh 😁
Is this already live on production? Because i didnt get an update prompt so i thought i have the latest version

**Comment by taleldayekh** [comment] 2020-07-31 09:15
> Is this already live on production?

It is on staging only at the moment. ;)

**Comment by taleldayekh** [comment] 2020-07-31 11:48
I'll close this issue since it is referencing an older design. The problem is solved and will be available upon the next release.

**Closed by taleldayekh** 2020-07-31 11:48 UTC
Labels: bug 💣, dApp 📱
