### ISSUE TITLE
Target is offline on the transfer screen

### ISSUE THREAD

**Issue by agatsoh** [raiden-network/light-client#1652] opened 2020-06-09 11:23 UTC
## Steps to Reproduce
1. Enter the address of the user you want to make a transfer with
2. 
![transfer_screen](https://user-images.githubusercontent.com/15123108/84141651-21019680-aa71-11ea-8a1d-411d130c296e.png)
Unfortunately i dont have the screenshot when the message was shown i reloaded the light client app and it worked.

## Expected Result
- The client was online as it was raiden node i operated from my machine. (discounting ofcourse all the message exchange which happens on the transport layer)

## Actual Result
- Target is offline

## Additional Infos (Optional) 
```
- Browser & version
Chrome Version 83.0.4103.97 (Official Build) (64-bit)
- Browser console errors
Screenshots are given above
`type: "path/find/failure", payload: RaidenError: Pathfinding Service is disabled and no direct route is available.`
- Device / OS
Linux mint
```

**Comment by andrevmatos** [comment] 2020-06-09 15:48
I couldn't reproduce it. Looks like you didn't either. Do you have logs? Maybe it was just a matter of time?

**Comment by christianbrb** [comment] 2020-06-11 12:24
Closing as it is not reproducible. Thanks @agatsoh for creating the issue :)

**Closed by christianbrb** 2020-06-11 12:24 UTC
