### ISSUE TITLE
RaidenError: nonce mismatch

### ISSUE THREAD

**Issue by agatsoh** [raiden-network/light-client#1933] opened 2020-07-21 12:43 UTC
## Steps to Reproduce
1. Should have withdrawn previously 
2. transfer to the light client or simply connecting to the light client

## Expected Result
- The light client should be synched with the correct nonce

## Actual Result
- The light client gets 
```
{
  "type": "transfer/failure",
  "payload": {
    "details": {
      "condition": false
    },
    "name": "RaidenError"
  },
  "meta": {
    "secrethash": "0xff588f59cf4e76fce7e56936ce2fc00b92c922d3886a490d0a8c1a480bac19fb",
    "direction": "received"
  },
  "error": true
}
```
![light_client_nonce_error](https://user-images.githubusercontent.com/15123108/88055794-2e846300-cb7d-11ea-927b-df93ef62c321.png)

[raiden_2020-07-21T12_29_18.130Z.log](https://github.com/raiden-network/light-client/files/4953463/raiden_2020-07-21T12_29_18.130Z.log)

Initiator node log

[node-F128A4-mainnet.21thJuly2020.log.tar.gz](https://github.com/raiden-network/light-client/files/4953529/node-F128A4-mainnet.21thJuly2020.log.tar.gz)

Mediating node logs 

[node-1Fd883-mainnet.21thJuly2020.log.tar.gz](https://github.com/raiden-network/light-client/files/4953534/node-1Fd883-mainnet.21thJuly2020.log.tar.gz)

## Additional Infos (Optional) 
```
- Browser & version
- Browser console errors
- Device / OS
```

**Comment by christianbrb** [comment] 2020-07-23 13:11
We are trying to reproduce the issue.

A better solution would be to do a resync.

It would need a protocol change

CC @Dominik1999 @karlb

**Comment by christianbrb** [comment] 2020-07-23 13:13
Additional information:
- @agatsoh's notebook crashed during withdraw

**Comment by christianbrb** [comment] 2020-07-23 13:18
Current issues look cut

**Comment by christianbrb** [comment] 2020-07-30 07:45
I wasn't able to reproduce the exact error, but I have managed to get my channel out of sync

I was doing the following things quite a few times to get to this state:
1. Making a withdraw or transfer
2. Closing Firefox with the task manager

Now I am not able to do withdrawals or transfers anymore. I don't see an error in the logs.

It is a channel with hub.raiden.eth. My address is 0x8c8492280cB454F2753DBb9a3114F4DA80F66714

Logs: 
[raiden_2020-07-30T07 38 51.453Z.log](https://github.com/raiden-network/light-client/files/4999662/raiden_2020-07-30T07.38.51.453Z.log)

**Comment by Dominik1999** [comment] 2020-07-30 09:45
Is this something we can help with? We will start normal working next week again

**Comment by christianbrb** [comment] 2020-07-30 10:01
@Dominik1999 Thanks for your support :) We need to do some investigation on the Raiden Hub first (get the logs). Afterwards we might reach out to you.

**Comment by eorituz** [comment] 2020-08-03 10:06
Here are the corresponding raiden logs:

[raiden_20200710.zip](https://github.com/raiden-network/light-client/files/5015273/raiden_20200710.zip)
[raiden_20200730.zip](https://github.com/raiden-network/light-client/files/5015274/raiden_20200730.zip)

**Comment by christianbrb** [comment] 2020-08-03 10:14
@eorituz Great, thanks :) I have updated your comment with a reference to the comments.

**Comment by christianbrb** [comment] 2020-08-04 08:04
@hackaugusto Is this maybe related to https://github.com/raiden-network/light-client/issues/2025?

**Comment by andrevmatos** [comment] 2020-08-04 12:22
I just ran BF1 scenario (#1948) replacing the node3 with a Raiden-py client (the other nodes running LC-CLI clients). This node3 gets withdrawn, and after it transfer from, to and through it, and the scenario passed, hinting, at least on the scenario, the nonce/message syncing is behaving as expected. So, it's either something not visible on the protocol side, or something "environmental", like state loss or network issues.

**Comment by christianbrb** [comment] 2020-08-04 12:30
@andrevmatos I think it is state loss. The messages are sent but not stored in the state because the computer or browser crashed before it could have been stored.

**Comment by christianbrb** [comment] 2020-08-04 14:16
We have decided to make an architectural change using IndexedDB.
- [ ] Reproduce the bug with a test @andrevmatos 
- [ ] Create an issue which describes the new design @andrevmatos

**Comment by christianbrb** [comment] 2020-08-06 07:52
Retest once #2044 is implemented. Moving it to the backlog

**Closed** 2020-09-24 13:55 UTC
Labels: bug 💣
