### ISSUE TITLE
Infinite signing loop when a transfer has been sent

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#843] opened 2020-01-08 09:50 UTC
## Steps to Reproduce
1. Open a channel to `0x5257964Ef9b81fba7276AF2a97c111AaD7B840D6`
2. Send a transfer to `0x5257964Ef9b81fba7276AF2a97c111AaD7B840D6`
3. Close the transfer modal window

## Expected Result
- After signing a few messages no more messages should get signed

## Actual Result
- The transfer was successful
- After signing a message I ALWAYS get a next message to sign

## Additional Infos (Optional) 
Console

## Possible solution
Finish work on issue #986 which might solve this problem. Currently, this problem is not reproducible.
```
Signing "Delivered" for "RevealSecret" with id=12334031938479595254
```

**Comment by christianbrb** [comment] 2020-01-08 11:43
After reconnecting I get this and MetaMask is still popping up:

![grafik](https://user-images.githubusercontent.com/35398162/71975522-7876ae80-3214-11ea-941b-8d98ba6b5df2.png)

**Comment by christianbrb** [comment] 2020-01-08 11:48
Now the target node seems to be stuck. I cannot send new transfers.

**Comment by christianbrb** [comment] 2020-01-08 12:48
Now I am confused ;)

After #836 I see 2 pending transfers and my channel balance went UP (I hope, that his is correct as I haven't taken a screenshot before).

![grafik](https://user-images.githubusercontent.com/35398162/71979229-7402c380-321d-11ea-99dd-cf222e86409f.png)

**Comment by andrevmatos** [comment] 2020-01-08 12:50
@christianbrb Did you recently clear your state? The first issue seems to be caused by your node somehow being ouf of sync with the hub. If so, please, close & settle any channel, you can open a new one with another hub,  or a new one with this after settling.

**Comment by christianbrb** [comment] 2020-01-13 09:31
No, I this was on a fresh channel.

**Comment by christianbrb** [comment] 2020-01-20 12:21
Maybe this is fixing the problem: https://github.com/raiden-network/raiden/pull/5581

CC @andrevmatos

**Comment by andrevmatos** [comment] 2020-01-30 21:27
No, @christianbrb , that won't solve it but may work around part of it. This is a very weird error, and means 2 weird things happening:
- the signing loop is caused by the hub retrying sending us a correct but expired `SecretReveal`
  - how this happened? we only reveal the secret to the target if it didn't expire yet, meaning the secret was requested **before** expiration and correctly revealed by us
  - the hub/partner/target didn't act on time (or you didn't sign the reveal on time) to reveal the secret back to us, but somehow did **after** the secret expired, continuing to hammer us with expired reveal which we won't unlock (but will expire soon)
- if the hub did know the secret but we didn't unlock, it should have gone register the secret on-chain and stop sending us these SecretReveal

I'm not sure how this occurred, but seems to be some kind of bug on the hub side. As the nodes got out of sync, only way forward is to close the channel and re-open it after settling.

It's hard to work around the `Delivered` signing prompts, as it's on transport. The PR you linked may workaround it by removing the Delivered message need, but the banging of invalid message will continue and isn't our fault. We can fail early though, and avoid the annoying error messages on the console. Besides this, we need to be able to handle the case when somehow the secret doesn't get back to us on time but is registered on chain. This shouldn't happen on the happy case, nor on the unhappy case if everyone works correctly by the protocol, but is a valid case, when we need to avoid expiring the lock (as it won't get accepted because the secret was registered on-chain on time), getting out of sync, and instead just leave the lock there to be unlocked after closing.

**Comment by taleldayekh** [comment] 2020-02-20 13:41
Finish work on issue #986 which might solve this problem. Currently, this problem is not reproducible.

**Closed by taleldayekh** 2020-02-20 13:41 UTC
Labels: bug 💣
