### ISSUE TITLE
Two times settling a channel leads to non-clickable token

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#286] opened 2019-08-27 06:42 UTC
## Steps to reproduce
1. Connect to Kovan
2. Open the dApp at lightclient.raiden.network
3. Settle only available channel (has not been a valid address)
3. Settle the channel a 2nd time
4. Going back to the token screen
5. Click on the WETH token

## Expected result

* Menu to pay, etc. opens

## Actual result

* Nothing happens (see 
[lightclient.raiden.network-1566887702277.log](https://github.com/raiden-network/light-client/files/3544629/lightclient.raiden.network-1566887702277.log)

* Warning:
`Adding default global override for .m.rule.tombstone`

* Errors:
`MetaMask - RPC Error: The execution failed due to an exception`
`Error: No seed provided`

## Actual result (after restart)

* Empty token list

**Comment by christianbrb** [comment] 2019-08-29 07:03
After a restart and reconnection the token list is empty

**Comment by nephix** [comment] 2019-09-17 07:25
@christianbrb I wasn't able to reproduce this

**Comment by nephix** [comment] 2019-09-23 17:45
I'm closing this one, as I can't reproduce it. I assume it got fixed within another bug fix

**Closed by nephix** 2019-09-23 17:45 UTC
Labels: bug 💣, dApp 📱
