### ISSUE TITLE
keccak@1.4.0 package issues

### ISSUE THREAD

**Issue by eorituz** [raiden-network/light-client#1828] opened 2020-06-29 14:53 UTC
## Steps to Reproduce
1.  Clone latest master 
2. run `cd light-client/raiden-ts && npm ci`

## Expected Result
Building without error messages. (The build finishes, however)

## Actual Result
Some issues with keccak dependency:
```
> keccak@1.4.0 rebuild /home/oliver/Arbeit/github/light-client/raiden-ts/node_modules/ganache-cli/node_modules/keccak
> node-gyp rebuild

make: Entering directory '/home/oliver/Arbeit/github/light-client/raiden-ts/node_modules/ganache-cli/node_modules/keccak/build'
  CXX(target) Release/obj.target/keccak/src/addon.o
In file included from ../src/addon.cc:2:
../../nan/nan.h: In function ‘void Nan::AsyncQueueWorker(Nan::AsyncWorker*)’:
../../nan/nan.h:2298:62: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
 2298 |     , reinterpret_cast<uv_after_work_cb>(AsyncExecuteComplete)
      |                                                              ^
../src/addon.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE KeccakWrapper::Initialize(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/addon.cc:37:47: error: no matching function for call to ‘v8::Value::IntegerValue()’
   37 |     unsigned int rate = info[0]->IntegerValue();
      |                                               ^
In file included from /home/oliver/.cache/node-gyp/12.18.0/include/node/node.h:67,
                 from ../src/addon.cc:1:
/home/oliver/.cache/node-gyp/12.18.0/include/node/v8.h:2705:40: note: candidate: ‘v8::Maybe<long int> v8::Value::IntegerValue(v8::Local<v8::Context>) const’
 2705 |   V8_WARN_UNUSED_RESULT Maybe<int64_t> IntegerValue(
      |                                        ^~~~~~~~~~~~
/home/oliver/.cache/node-gyp/12.18.0/include/node/v8.h:2705:40: note:   candidate expects 1 argument, 0 provided
../src/addon.cc:38:51: error: no matching function for call to ‘v8::Value::IntegerValue()’
   38 |     unsigned int capacity = info[1]->IntegerValue();
      |                                                   ^
In file included from /home/oliver/.cache/node-gyp/12.18.0/include/node/node.h:67,
                 from ../src/addon.cc:1:
/home/oliver/.cache/node-gyp/12.18.0/include/node/v8.h:2705:40: note: candidate: ‘v8::Maybe<long int> v8::Value::IntegerValue(v8::Local<v8::Context>) const’
 2705 |   V8_WARN_UNUSED_RESULT Maybe<int64_t> IntegerValue(
      |                                        ^~~~~~~~~~~~
/home/oliver/.cache/node-gyp/12.18.0/include/node/v8.h:2705:40: note:   candidate expects 1 argument, 0 provided
../src/addon.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE KeccakWrapper::AbsorbLastFewBits(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/addon.cc:56:48: error: no matching function for call to ‘v8::Value::IntegerValue()’
   56 |     unsigned char bits = info[0]->IntegerValue();
      |                                                ^
In file included from /home/oliver/.cache/node-gyp/12.18.0/include/node/node.h:67,
                 from ../src/addon.cc:1:
/home/oliver/.cache/node-gyp/12.18.0/include/node/v8.h:2705:40: note: candidate: ‘v8::Maybe<long int> v8::Value::IntegerValue(v8::Local<v8::Context>) const’
 2705 |   V8_WARN_UNUSED_RESULT Maybe<int64_t> IntegerValue(
      |                                        ^~~~~~~~~~~~
/home/oliver/.cache/node-gyp/12.18.0/include/node/v8.h:2705:40: note:   candidate expects 1 argument, 0 provided
../src/addon.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE KeccakWrapper::Squeeze(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/addon.cc:64:43: error: no matching function for call to ‘v8::Value::IntegerValue()’
   64 |     size_t length = info[0]->IntegerValue();
      |                                           ^
In file included from /home/oliver/.cache/node-gyp/12.18.0/include/node/node.h:67,
                 from ../src/addon.cc:1:
/home/oliver/.cache/node-gyp/12.18.0/include/node/v8.h:2705:40: note: candidate: ‘v8::Maybe<long int> v8::Value::IntegerValue(v8::Local<v8::Context>) const’
 2705 |   V8_WARN_UNUSED_RESULT Maybe<int64_t> IntegerValue(
      |                                        ^~~~~~~~~~~~
/home/oliver/.cache/node-gyp/12.18.0/include/node/v8.h:2705:40: note:   candidate expects 1 argument, 0 provided
../src/addon.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE KeccakWrapper::Copy(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/addon.cc:75:82: error: no matching function for call to ‘v8::Value::ToObject()’
   75 |     KeccakWrapper* to = Nan::ObjectWrap::Unwrap<KeccakWrapper>(info[0]->ToObject());
      |                                                                                  ^
In file included from /home/oliver/.cache/node-gyp/12.18.0/include/node/node.h:67,
                 from ../src/addon.cc:1:
/home/oliver/.cache/node-gyp/12.18.0/include/node/v8.h:2672:44: note: candidate: ‘v8::MaybeLocal<v8::Object> v8::Value::ToObject(v8::Local<v8::Context>) const’
 2672 |   V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
      |                                            ^~~~~~~~
/home/oliver/.cache/node-gyp/12.18.0/include/node/v8.h:2672:44: note:   candidate expects 1 argument, 0 provided
In file included from /home/oliver/.cache/node-gyp/12.18.0/include/node/v8-internal.h:14,
                 from /home/oliver/.cache/node-gyp/12.18.0/include/node/v8.h:27,
                 from /home/oliver/.cache/node-gyp/12.18.0/include/node/node.h:67,
                 from ../src/addon.cc:1:
/home/oliver/.cache/node-gyp/12.18.0/include/node/v8.h:2686:31: note: candidate: ‘v8::Local<v8::Object> v8::Value::ToObject(v8::Isolate*) const’
 2686 |                 Local<Object> ToObject(Isolate* isolate) const);
      |                               ^~~~~~~~
/home/oliver/.cache/node-gyp/12.18.0/include/node/v8config.h:328:3: note: in definition of macro ‘V8_DEPRECATED’
  328 |   declarator __attribute__((deprecated(message)))
      |   ^~~~~~~~~~
/home/oliver/.cache/node-gyp/12.18.0/include/node/v8.h:2686:31: note:   candidate expects 1 argument, 0 provided
 2686 |                 Local<Object> ToObject(Isolate* isolate) const);
      |                               ^~~~~~~~
/home/oliver/.cache/node-gyp/12.18.0/include/node/v8config.h:328:3: note: in definition of macro ‘V8_DEPRECATED’
  328 |   declarator __attribute__((deprecated(message)))
      |   ^~~~~~~~~~
In file included from ../src/addon.cc:1:
../src/addon.cc: At global scope:
/home/oliver/.cache/node-gyp/12.18.0/include/node/node.h:608:43: warning: cast between incompatible function types from ‘void (*)(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE, Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Object>)’} to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]
  608 |       (node::addon_register_func) (regfunc),                          \
      |                                           ^
/home/oliver/.cache/node-gyp/12.18.0/include/node/node.h:642:3: note: in expansion of macro ‘NODE_MODULE_X’
  642 |   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
      |   ^~~~~~~~~~~~~
../src/addon.cc:86:1: note: in expansion of macro ‘NODE_MODULE’
   86 | NODE_MODULE(keccak, Init)
      | ^~~~~~~~~~~
make: *** [keccak.target.mk:129: Release/obj.target/keccak/src/addon.o] Error 1
make: Leaving directory '/home/oliver/Arbeit/github/light-client/raiden-ts/node_modules/ganache-cli/node_modules/keccak/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 5.4.0-37-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/oliver/Arbeit/github/light-client/raiden-ts/node_modules/ganache-cli/node_modules/keccak
gyp ERR! node -v v12.18.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! keccak@1.4.0 rebuild: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the keccak@1.4.0 rebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/oliver/.npm/_cacache/_logs/2020-06-29T14_47_22_907Z-debug.log
Keccak bindings compilation fail. Pure JS implementation will be used.
```

## Additional Infos (Optional) 
```
oliver@bbpc:~/Arbeit/github/light-client/raiden-ts$ npm -v && node -v
6.14.4
v12.18.0
```
[Full npm ci logs](https://github.com/raiden-network/light-client/files/4846247/npm_ci.log)

**Comment by christianbrb** [comment] 2020-07-27 07:36
@eorituz Thanks for reporting the issue. Is this still a problem?

**Comment by andrevmatos** [comment] 2020-07-27 14:49
This is a known error, caused by `ganache-cli` trying to build an old version of `keccak` which isn't compatible with node12+. It'd be only used as an optimization though, and only for tests, as it falls back to pure-js implementation. It is non-fatal, just an optional native optimization for a test dependency. https://github.com/trufflesuite/ganache-cli/issues/591

**Comment by taleldayekh** [comment] 2021-06-18 13:54
@agatsoh give it a go and close or keep open when you know the outcome.

**Comment by agatsoh** [comment] 2021-06-24 12:08
@taleldayekh  As of raiden 1.0.0 release `yarn install` gives this error on the raspberry pi 4 8GB.
The steps that I used to get here are documented in this [gist](https://gist.github.com/agatsoh/d333db1ac2eb17844aea69fde5fac747). I am doing further research but if anyone already has an idea how to correct it please post it here. Thanks !!!
```
$ yarn install
yarn install v1.22.10
$ npx only-allow yarn
npx: installed 25 in 5.172s
[1/4] Resolving packages...
warning Resolution field "typescript@4.2.4" is incompatible with requested version "typescript@~4.1.5"
[2/4] Fetching packages...
info fsevents@2.3.2: The platform "linux" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "workspace-aggregator-022d7814-4f43-44fe-be84-fb1c7c80eebd > raiden-dapp > @cypress/webpack-preprocessor@5.9.0" has unmet peer dependency "@babel/preset-env@^7.0.0".
warning "workspace-aggregator-022d7814-4f43-44fe-be84-fb1c7c80eebd > raiden-dapp > @vue/cli-plugin-eslint@4.5.13" has incorrect peer dependency "eslint@>= 1.6.0 < 7.0.0".
warning "workspace-aggregator-022d7814-4f43-44fe-be84-fb1c7c80eebd > raiden-dapp > eslint-plugin-vue-i18n@0.3.0" has incorrect peer dependency "eslint@^5.0.0 || ^6.0.0".
warning "workspace-aggregator-022d7814-4f43-44fe-be84-fb1c7c80eebd > raiden-dapp > @vue/cli-plugin-eslint > eslint-loader@2.2.1" has incorrect peer dependency "eslint@>=1.6.0 <7.0.0".
warning "workspace-aggregator-022d7814-4f43-44fe-be84-fb1c7c80eebd > raiden-dapp > cypress > listr2@3.10.0" has unmet peer dependency "enquirer@>= 2.3.0 < 3".
warning "workspace-aggregator-022d7814-4f43-44fe-be84-fb1c7c80eebd > raiden-dapp > eslint-plugin-vue-i18n > vue-eslint-parser@6.0.5" has incorrect peer dependency "eslint@^5.0.0 || ^6.0.0".
warning "wrtc@0.4.7" is missing a bundled dependency "node-pre-gyp". This should be reported to the package maintainer.
[4/4] Building fresh packages...
[10/16] ⠁ cypress
[9/16] ⠁ ejs
[3/16] ⠂ keccak
[4/16] ⠂ secp256k1
error /home/pi/light-client/node_modules/cypress: Command failed.
Exit code: 1
Command: node index.js --exec install
Arguments: 
Directory: /home/pi/light-client/node_modules/cypress
Output:
Installing Cypress (version: 7.5.0)

[STARTED] Task without title.
The Cypress App could not be downloaded.

Does your workplace require a proxy to be used to access the Internet? If so, you must configure the HTTP_PROXY environment variable before downloading Cypress. Read more: https://on.cypress.io/proxy-configuration

Otherwise, please check network connectivity and try again:

----------

URL: https://download.cypress.io/desktop/7.5.0?platform=linux&arch=ia32
Error: Failed downloading the Cypress binary.
Response code: 404
Response message: Not Found

----------

Platform: linux (Debian - 10)
Cypress Version: 7.5.0
[FAILED] The Cypress App could not be downloaded.
[FAILED] 
[FAILED] Does your workplace require a proxy to be used to access the Internet? If so, you must configure the HTTP_PROXY environment variable before downloading Cypress. Read more: https://on.cypress.io/proxy-configuration
[FAILED] 
[FAILED] Otherwise, please check network connectivity and try again:
[FAILED] 
[FAILED] ----------
[FAILED] 
[FAILED] URL: https://download.cypress.io/desktop/7.5.0?platform=linux&arch=ia32
[FAILED] Error: Failed downloading the Cypress binary.
[FAILED] Response code: 404
[FAILED] Response message: Not Found
[FAILED] 
[FAILED] ----------
```

**Comment by taleldayekh** [comment] 2021-06-29 12:59
Closing, this has been resolved with the removal of ganache.

**Closed by taleldayekh** 2021-06-29 12:59 UTC
Labels: refactor
