### ISSUE TITLE
"Try Out the Raiden Demo dApp" README.md changes required

### ISSUE THREAD

**Issue by mat7ias** [raiden-network/light-client#398] opened 2019-10-17 15:30 UTC
## User Story
The [Try Out the Raiden Demo dApp](https://github.com/raiden-network/light-client#try-out-the-raiden-demo-dapp) guide is now outdated.
Since the [Raiden dApp](http://lightclient.raiden.network) has been updated, the Ropsten (v0.100.2) node linked in the guide is no longer compatible with hosted the light client. I've started a node that can be interacted with the current light client on Goerli (rather than Ropsten) under the same address (0x5257964Ef9b81fba7276AF2a97c111AaD7B840D6) and same ENS (mat7ias.eth). I've tested it to confirm light clients are able to send TTT on Görli successfully via light client to this node.

## Acceptance criteria
The guide is updated to reflect the changes of the light client that's hosted at http://lightclient.raiden.network.

## Tasks
If the same node is used (which should be fine):
- Change intro for the section to be "We will be using the Goerli testnet and MetaMask wallet in this example"
- Change Prerequisites section - "Select the Goerli Test Network when you've logged in to your MetaMask."
- Change step 1 section - no.1: Update the faucet to be https://faucet.goerli.mudit.blog, or an alternative
no.2: "Enter the wallet address associated with your Goerli Test Network."
no.3: if WETH isn't being used this will need to be adjusted
no.4-7: https://0x.org/portal/weth on Görli will not work for now, until 0x v3 at least. Either a suggestion to ask the community in community channels (already happens relatively frequently) or get TTT which can be done via etherscan+metamask [writing to the contract](https://goerli.etherscan.io/address/0x3ed0daedc3217615bde34fedd023bc81ae49251b#writeContract) (UX isn't as nice as 0x wrapping, should be temporary though): "Connect to Web3", "mint", "amount"
- Change step 2 section - no.2 if token from above steps is changed from WETH to TTT, this point needs to be adjusted

**Comment by nephix** [comment] 2019-10-17 16:30
Related/duplicate of #393

**Comment by mat7ias** [comment] 2019-10-18 01:24
Ah yep, I didn't see that one. I'd just finished changing my node over to Goerli and tried it out with the light client to make sure it worked for testing. Maybe some of the info in this is still useful depending on what you decide to do. Feel free to close whenever :)

**Comment by nephix** [comment] 2019-10-18 03:31
Thank you @mat7ias :)

**Comment by christianbrb** [comment] 2019-10-18 06:12
@mat7ias Great, thanks for setting up and running the node. It is more convenient for users to interact with your Node. We'll follow that approach.

CC @taleldayekh

**Comment by taleldayekh** [comment] 2019-10-18 09:20
Cool, thanks @mat7ias . I'll update it as soon as I get a chance.

**Comment by taleldayekh** [comment] 2019-10-18 12:08
I need to look into how to best explain the "Writing to the contract"-step for acquiring TTT. I guess that's the perferred way because then you don't need to ask anyone but can do it youself.

**Comment by mat7ias** [comment] 2019-10-19 08:36
@taleldayekh Just as an idea, could include something similar to this gif ![mint](https://user-images.githubusercontent.com/35585644/67139818-0be8b500-f2a0-11e9-91b0-c8d630bb710b.gif) along with the contract and an easy [add TTT token](https://metamask.github.io/Add-Token/index.html?tokenImage=https://goerli.etherscan.io/images/main/empty-token.png&tokenName=TTT&tokenAddress=0x3ed0DaEDC3217615bde34FEDd023bC81ae49251B&tokenNet=5&tokenSymbol=TTT&tokenDecimals=18) for metamask (used in the gif).

**Comment by taleldayekh** [comment] 2019-10-19 08:40
Yes, that's a very nice idea @mat7ias !

**Comment by taleldayekh** [comment] 2019-10-21 09:50
Made this gif now, I skipped the "watch token" step to make it more straight to the point. I assume "watch token" is not necessary, correct me if I'm wrong.

![TTT](https://user-images.githubusercontent.com/43838780/67195145-ba077280-f3f8-11e9-9b70-0ceb9eec1952.gif)

**Comment by mat7ias** [comment] 2019-10-21 12:23
@taleldayekh correct, it's not necessary. Was more just in case it was something you wanted to include. Looks great!

**Comment by taleldayekh** [comment] 2019-10-22 09:06
Thanks for all the input and help @mat7ias . I have now merged the updated version and will close this issue.

**Closed by taleldayekh** 2019-10-22 09:06 UTC
