### ISSUE TITLE
Channel close rejection gets not recognized

### ISSUE THREAD

**Issue by weilbith** [raiden-network/light-client#1695] opened 2020-06-12 12:57 UTC
## Steps to Reproduce
1. Open a channel (do not deposit yet)
2. Go to the channel list and click `close`
3. Reject the popping MetaMask transaction window
4. Try to deposit tokens

## Expected Result
- I can click on deposit

## Actual Result
- Trying to deposit brings up the generic error pop-up
- Te channels state is in state `closed` **BUT** I can't settle and must click/execute `close` again (which is basically correct, because first time has been rejected)

## Additional Infos (Optional) 
```
- Browser & version: `Mozilla Firefox 74.0`
- Browser console errors: none as I can see
- Device / OS: `5.5.11-arch1-1`
```

**Comment by andrevmatos** [comment] 2020-06-12 13:35
Actually, this is kind of by design and is working as intended (at least for now, but we can use this issue to reconsider).

The rationale is that the channel becomes `closing` whenever any sign of closing intent happens, so the channel doesn't get used anymore to receive transfers and possibly lose them if accepting a out-of-time message. This is true for e.g. when first seeing a closing tx on-chain, even if it isn't confirmed yet and may be reorged and removed later, we already mark the channel as `closing`, and the only way out is actually closing/settling it. To avoid mistakenly doing this, there should be a confirmation dialog between clicking close and signing the tx.
What you seem to expect is that it'd only become `closing` after the prompt was accepted. I think it'd be equally valid, it's just a matter of decision and taste.
@christianbrb any thoughts on this? What'd be the best approach for UX?

**Comment by weilbith** [comment] 2020-06-12 13:43
Okay, reading you explanation makes totally sense. But I agree that an UI improvement would be helpful for the unexperienced user. I actually wanted to close the view btw. and attempted to cancel that mistake :joy:

**Comment by christianbrb** [comment] 2020-06-22 09:46
Retested and there is already a message "Do you really want to close the channel?"

If I reject the MetaMask message, the channel should be usable again. Maybe there is a resync with the blockchain needed afterward.

**Comment by weilbith** [comment] 2020-06-22 09:55
Okay I have absolutely no clue how I missed why while doing experiments with Talel. Sorry for wasting your time twice. :see_no_evil: :expressionless:

**Comment by christianbrb** [comment] 2020-06-22 09:56
@weilbith It was a good catch and the message "Do you really want to close the channel?" is not sufficient as a solution to that problem.

**Comment by christianbrb** [comment] 2020-06-25 13:18
Workaround: Click on Close again

**Closed by christianbrb** 2020-06-25 13:18 UTC
Labels: Ready 🎬, bug 💣, dApp 📱
